baseURL = "https://3600.lat/test/"
title = "3600.lat"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = "🄯 2018 - 3600.lat"

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "creada en 2018, desde la altura de La Paz"
title404 = "Error - algo falló."

[params.assets]
favicon = "favicon.png"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "3600.lat"
startYear = "2018"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "02 Jan 2006"
listDateFormat = "02 Jan 2006"
archiveDateFormat = "02 Jan"
hideEntryNavigation = ["page"] # boolean / array of sections
showReadingTime = true
taxonomyCloudShuffle = true
accentColor = "#0095FF"
hideMainMenu = false

[params.sidebar]
enable = true

[params.widgets]
#homepage = ["recent_posts"]
homepage = []
sidebar = ["about","sidebar_menu"]
#sidebar = ["about","search","sidebar_menu", "taxonomies"]
footer = ["social_menu"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "3600LAT" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
email = "contacto@3600.lat"
facebook = "3600.lat"
#github = "MunifTanjim"
#gitlab = "Mun"
#instagram = "MunifTanjim"
linkedin_company = "3600-lat"
twitter = "3600LAT"
#telegram = "MunifTanjim"
youtube = "UCxC6dQTYyV2ewsthbsql26A"
youtube_name = "3600.LATBOL"

[params.direccion]
url = "https://www.openstreetmap.org/?mlat=-16.506767570972443&mlon=-68.13326954841614#map=18/-16.50677/-68.13327"
direccion = ["Edificio Qhana, planta baja / L-2", "Nº522 calle Landaeta, Sopocachi", "La Paz", "Bolivia"]

[params.personas.rmolina]
nombre = "Fernando Molina"
foto = "images/rmolina.jpg"
presentacion = "Profesional geógrafo, modeliza e interpreta el territorio mediante mapas; crea, analiza y visualiza datos, genera simbologías"
celular = "+591-72000576"
correo = "rmolina@3600.lat"
mensajerias = ["signalapp", "whatsapp"]
paginapropia = "https://rincondelosgeografos.blogspot.com/"

[params.personas.rmolina.social]
twitter = "https://twitter.com/rafemoro"
github = "https://github.com/rafemoro"
linkedin = "https://www.linkedin.com/in/rafemoro/"
graduation-cap = "https://www.researchgate.net/profile/Raul_Molina-Rodriguez"

[params.personas.slesage]
nombre = "Sylvain Lesage"
foto = "images/slesage.jpg"
presentacion = "Desarrolla software, diseña mapas, analiza datos y aplica algoritmos."
celular = "+591-71542024"
correo = "slesage@3600.lat"
mensajerias = ["signalapp", "telegram"]
paginapropia = "https://rednegra.net/sylvainlesage"

[params.personas.slesage.social]
twitter = "https://twitter.com/mapsinbolivia"
mastodon = "https://mamot.fr/@severo_bo"
quote-right = "https://seenthis.net/people/severo"
linkedin = "https://www.linkedin.com/in/sylvain-lesage-42793015a/"
keybase = "https://keybase.io/severo"
github = "https://github.com/severo"
gitlab = "https://framagit.org/severo"
graduation-cap = "https://www.researchgate.net/scientific-contributions/57113422_Sylvain_Lesage"

[params.comments]
enable = false

[params.comments.staticman]
enable = true
apiEndpoint = "https://api.staticman.net/v2/entry"
maxDepth = 2

[params.comments.staticman.github]
username = "MunifTanjim"
repository = "minimo"
branch = "master"

# Utterances: https://utteranc.es
[params.comments.utterances]
enable = false
issueTerm = "pathname" # pathname / url / title

[params.comments.utterances.github]
username = "MunifTanjim"
repository = "minimo"

[params.search]
client = "" # algolia / fuse / lunr

[params.search.algolia]
appId = ""
indexName = ""
searchApiKey = ""

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

#[[menu.main]]
#name = "Repo"
#weight = -10
#identifier = "repository"
#url = "https://github.com/MunifTanjim/minimo"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1

[languages.es]
lang = "es"
languageName = "Español"
weight = 1

[languages.fr]
lang = "fr"
languageName = "Français"
weight = 1
